Do smth to make it work
PragmaticsLab/NLGEval pull request #14
Opened 2023-05-12 15:01 UTC by CUPalex

- удалила MNLI_BERT из MoverScore, вместе него вставила берт из хаггингфейса, когда все из хаггингфейса гораздо проще жить
- чуть написала ридми, чтобы выглядело поприличней, возможно, его потом все равно надо будет дописывать
- добавила возможность в бертскоре считать recall и precision
- переустановила все библиотеки с poetry чтобы оно наконец заработало, потому что до этого почему-то не запускалось. возможно, это было и проблема была не в poetry, но предлагаю не трогать то что работает.

2023-05-14 12:01 UTC, MaratSaidov commented
Есть общий наброс: при запуске `pytest tests` в новом окружении какая-то стена ошибок.
Но предлагаю пока не обращать внимание.

2023-05-14 12:01 UTC, MaratSaidov requested changes

2023-05-14 12:05 UTC, MaratSaidov commented on nlgeval/metrics/pretrained.py
> +        self.mode = mode
будем бросать ошибку, если `mode` некорректный?

2023-05-14 12:08 UTC, MaratSaidov commented on pyproject.toml
> +python = ">=3.8,<3.12"
А ты проверяла для 3.8 и 3.11, что заведется?
Я только для 3.10 смотрел.

2023-05-14 12:09 UTC, MaratSaidov commented on pyproject.toml
> +python = ">=3.8,<3.12"
То есть нестрашно, если мы говорим использовать те версии, для которых уверены.
И ругать на этапе установки, если у людей слишком старый python.

2023-05-15 16:53 UTC, CUPalex commented on poetry.lock
Опять же, зачем, если вроде с poetry работает?

2023-05-15 16:55 UTC, CUPalex commented on nlgeval/metrics/pretrained.py
> +        self.mode = mode
давай

2023-05-15 16:55 UTC, CUPalex commented on pyproject.toml
> +python = ">=3.8,<3.12"
Для 3.8 проверяла (тесты не прогоняла, просто с дефолтными настройками запускала), для остальных нет

2023-05-15 17:37 UTC, MaratSaidov commented on poetry.lock
ну ладно, это опциональный наброс. показалось, что тебе неудобно.

2023-05-15 17:38 UTC, MaratSaidov commented on pyproject.toml
> +python = ">=3.8,<3.12"
давай зафиксируем 3.8, 3.9, 3.10 тогда

2023-05-15 17:42 UTC, MaratSaidov commented on pyproject.toml
> +numpy = "^1.24.3"
ага, я несколько раз об это спотыкался: в какой-нибудь версии меняется функционал - падаем с ошибкой.
новую библиотеку добавить проще, чем осознать, как менялась логика в разных версиях какой-то второстепенной либы.

2023-05-24 10:06 UTC, CUPalex commented on README.md
> +### Evaluations metrics
https://gist.github.com/CUPalex/8b415e332f8efbafd10d96de50a84c21

2023-06-08 08:34 UTC, MaratSaidov approved these changes

2023-06-08 08:35 UTC, merged